apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-bfatpp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-bfatpp
    app.kubernetes.io/part-of: jvm-build-suite-application-dydp
  name: jvm-build-suite-component-bfatpp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-bfatpp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-bfatpp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-bkde-tenant/jvm-build-suite-application-dydp/jvm-build-suite-component-bfatpp@sha256:d358946d64d400dda227aafde907e42ac98fa2c79c5b386eb18052e97757a62d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
