apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-bfatpp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-bkde-tenant/jvm-build-suite-application-dydp/jvm-build-suite-component-bfatpp@sha256:d358946d64d400dda227aafde907e42ac98fa2c79c5b386eb18052e97757a62d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
